# Generated by Django 4.2.9 on 2024-01-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='province',
            new_name='state',
        ),
    ]
